services:
  tests:
    image: buildkite/plugin-tester:v4.1.1
    volumes:
      - ".:/plugin:ro"

  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'lambdatest/lambdatest']
    volumes:
      - ".:/plugin:ro"
