version: '3.7'
services:
  tests:
    image: buildkite/plugin-tester:v4.0.0
    volumes:
      - ".:/plugin"
      
  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'a-github-user/file-counter']
    volumes:
      - ".:/plugin:ro"